### ISSUE TITLE
Any plans for a Craft 3 version?

### ISSUE THREAD

**Issue by SimonEast** [trendyminds/visor#5]
We've found this plugin really helpful. Just wondering whether it's still maintained anymore? Does anyone have plans for a Craft 3 version?

**Comment by aaronbushnell** [comment]
Hey @SimonEast—we'll definitely create a Craft 3 version! Thanks for sharing your interest in it. I'll respond in this issue once we have it finished 👍

**Comment by aaronbushnell** [comment]
@SimonEast The 3.x version is now in `master` and can be installed using `composer require trendyminds/visor` or through the Plugin Store once approved. Thanks!

**Comment by aaronbushnell** [comment]
Also, don't hesitate to reach out if something doesn't behave as expected! :)

**Comment by aaronbushnell** [comment]
Now available in the plugin store: https://plugins.craftcms.com/visor
