### ISSUE TITLE
Edit Entry only works for admin

### ISSUE THREAD

**Issue by pioneerdesign** [trendyminds/visor#7]
It appears that the "Edit Entry" link/icon only shows up for admin users. For other user groups that link disappears but the other links are there like All Entries. Is there any way to get the Edit Entry link to work for all user groups?

**Comment by aaronbushnell** [comment]
Hey @pioneerdesign! The "Edit Entry" link is available only to the users who can access that section. You can see how that [conditional logic shakes out here](https://github.com/trendyminds/visor/blob/master/src/templates/visor.twig#L30-L37).

Does this user have access to this particular content type in Craft?

**Comment by pioneerdesign** [comment]
I've verified this user has access to this (and all other) sections. When logged in as that user the links do not include Edit Entry.

**Comment by aaronbushnell** [comment]
Ah, I see the issue and this will be fixed in 2.0.5!
